from abc import ABCMeta, abstractmethod
from pathlib import Path
from typing_extensions import (Any, Callable, ClassVar, Final, Iterable, Iterator, List, NamedTuple, Optional,
                               OrderedDict, Self, Sequence, Tuple, Type, TypeVar, Union, override)

class SectionError(Exception): ...

class CycleError(SectionError): ...

class MultiValueError(SectionError):
    fst_type: Type
    type: Type

    def __init__(self, fst_type: Type, type_: Type) -> None: ...

class IncludeError(SectionError): ...

class NoCDKPathError(IncludeError):
    path: Path

    def __init__(self, path: Path) -> None: ...

class NoRootPathError(IncludeError):
    path: Path

    def __init__(self, path: Path) -> None: ...

class LoadFileError(IncludeError):
    path: Path
    working_path: Path
    cdk_path: Optional[Path]
    root_path: Optional[Path]

    def __init__(self, path: Path, working_path: Path, cdk_path: Optional[Path], root_path: Optional[Path]) -> None: ...

class Var:
    value: Any

    def __init__(self, init: Any) -> None: ...

class Value: ...

class Parameter(Value): ...

class Scalar(Parameter): ...

class Bool(int, Scalar): ...

true: Bool
false: Bool

class EncodedStr(str):
    encodings: Final[ClassVar[Tuple[str, ...]]]

    @classmethod
    def of(cls, xs: Any) -> 'EncodedStr': ...

class Str(EncodedStr, Scalar):
    @classmethod
    def of(cls, xs: Any) -> 'Str': ...

def SafeStr(xs: Any) -> Str: ...

class Int(int, Scalar):
    signed: Final[ClassVar[bool]]
    max_bit_length: Final[ClassVar[int]]
    min: Final[ClassVar[int]]
    max: Final[ClassVar[int]]
    fmt: Final[ClassVar[str]]

    @classmethod
    def of(cls, x: Any) -> 'Int': ...

    @classmethod
    def validated(cls, x: Any) -> int: ...

def SafeInt(x: Any) -> Int: ...

class UByte(int, Scalar):
    signed: Final[ClassVar[bool]]
    max_bit_length: Final[ClassVar[int]]
    min: Final[ClassVar[int]]
    max: Final[ClassVar[int]]
    fmt: Final[ClassVar[str]]

    @classmethod
    def of(cls, x: Any) -> 'Int': ...

    @classmethod
    def validated(cls, x: Any) -> int: ...

def SafeUByte(x: Any) -> Int: ...

class Long(int, Scalar):
    signed: Final[ClassVar[bool]]
    max_bit_length: Final[ClassVar[int]]
    min: Final[ClassVar[int]]
    max: Final[ClassVar[int]]
    fmt: Final[ClassVar[str]]

    @classmethod
    def of(cls, x: Any) -> 'Int': ...

    @classmethod
    def validated(cls, x: Any) -> int: ...

def SafeLong(x: Any) -> Int: ...

Number = TypeVar('Number', int, float)

class Float(float, Scalar):
    rel_tol: Final[ClassVar[float]]
    abs_tol: Final[ClassVar[float]]
    fmt: Final[ClassVar[str]]

    @classmethod
    def of(cls, x: Any) -> 'Float': ...

    @classmethod
    def validated(cls, x: Any) -> float: ...

    def close_to(self, other: Number) -> bool: ...

def SafeFloat(x: Any) -> Float: ...

class Vector(Tuple[Number], Parameter, metaclass=ABCMeta):
    type: ClassVar[Type[Union[Float, Int, UByte]]]
    size: ClassVar[int]

    @classmethod
    def of(cls, xs: Any) -> 'Vector': ...

    def close_to(self, other: Sequence) -> bool: ...

class Int2(Vector[int]):
    @classmethod
    def of(cls, xs: Any) -> 'Int2': ...

def SafeInt2(xs: Any) -> 'Int2': ...

class Int3(Vector[int]):
    @classmethod
    def of(cls, xs: Any) -> 'Int3': ...

def SafeInt3(xs: Any) -> 'Int3': ...

class Color(Vector[int]):
    @classmethod
    def of(cls, xs: Any) -> 'UByte': ...

def SafeColor(xs: Any) -> 'UByte': ...

class Float2(Vector[float]):
    @classmethod
    def of(cls, xs: Any) -> 'Float2': ...

def SafeFloat2(xs: Any) -> 'Float2': ...

class Float3(Vector[float]):
    @classmethod
    def of(cls, xs: Any) -> 'Float3': ...

def SafeFloat3(xs: Any) -> 'Float3': ...

class Float4(Vector[float]):
    @classmethod
    def of(cls, xs: Any) -> 'Float4': ...

def SafeFloat4(xs: Any) -> 'Float4': ...

class Float12(Vector[float]):
    @classmethod
    def of(cls, xs: Any) -> 'Float12': ...

def SafeFloat12(xs: Any) -> 'Float12': ...

class Name(EncodedStr):
    of_root: Final[ClassVar[None]]

    @classmethod
    def of(cls, xs: Any) -> 'Name': ...


def SafeName(xs: Any) -> 'Name': ...

Item = Tuple[Name, Value]
Default = TypeVar('Default')

class Size(NamedTuple):
    params_count: int
    blocks_count: int

class Section(Value, metaclass=ABCMeta):
    @classmethod
    def of(cls, section: 'Section') -> 'Section': ...

    @abstractmethod
    def append(self, item: Item) -> None: ...

    @abstractmethod
    def add(self, name: str, value: Value) -> None: ...

    @abstractmethod
    def get(self, name: str, index: int = 0, default: Default = None) -> Union[Value, Default]: ...

    def get_first(self, name: str, default: Default = None) -> Union[Value, Default]: ...

    @abstractmethod
    def get_all(self, name: str, default: Default = ...) -> Union[List[Value], Default]: ...

    def get_section(self, name: str, index: int = 0, default: Default = None) -> Union['Section', Default]: ...

    def get_str(self, name: str, index: int = 0, default: Default = None) -> Union[Str, Default]: ...

    def get_int(self, name: str, index: int = 0, default: Default = None) -> Union[Int, Default]: ...

    def get_float(self, name: str, index: int = 0, default: Default = None) -> Union[Float, Default]: ...

    def get_float2(self, name: str, index: int = 0, default: Default = None) -> Union[Float2, Default]: ...

    def get_float3(self, name: str, index: int = 0, default: Default = None) -> Union[Float3, Default]: ...

    def get_float4(self, name: str, index: int = 0, default: Default = None) -> Union[Float4, Default]: ...

    def get_int2(self, name: str, index: int = 0, default: Default = None) -> Union[Int2, Default]: ...

    def get_int3(self, name: str, index: int = 0, default: Default = None) -> Union[Int3, Default]: ...

    def get_bool(self, name: str, index: int = 0, default: Default = None) -> Union[Bool, Default]: ...

    def get_color(self, name: str, index: int = 0, default: Default = None) -> Union[Color, Default]: ...

    def get_float12(self, name: str, index: int = 0, default: Default = None) -> Union[Float12, Default]: ...

    def get_long(self, name: str, index: int = 0, default: Default = None) -> Union[Long, Default]: ...

    def get_first_section(self, name: str, default: Default = None) -> Union['Section', Default]: ...

    def get_first_str(self, name: str, default: Default = None) -> Union[Str, Default]: ...

    def get_first_int(self, name: str, default: Default = None) -> Union[Int, Default]: ...

    def get_first_float(self, name: str, default: Default = None) -> Union[Float, Default]: ...

    def get_first_float2(self, name: str, default: Default = None) -> Union[Float2, Default]: ...

    def get_first_float3(self, name: str, default: Default = None) -> Union[Float3, Default]: ...

    def get_first_float4(self, name: str, default: Default = None) -> Union[Float4, Default]: ...

    def get_first_int2(self, name: str, default: Default = None) -> Union[Int2, Default]: ...

    def get_first_int3(self, name: str, default: Default = None) -> Union[Int3, Default]: ...

    def get_first_bool(self, name: str, default: Default = None) -> Union[Bool, Default]: ...

    def get_first_color(self, name: str, default: Default = None) -> Union[Color, Default]: ...

    def get_first_float12(self, name: str, default: Default = None) -> Union[Float12, Default]: ...

    def get_first_long(self, name: str, default: Default = None) -> Union[Long, Default]: ...

    @abstractmethod
    def get_all_sections(self, name: str, default: Default = ...) -> Union[List['Section'], Default]: ...

    @abstractmethod
    def get_all_strs(self, name: str, default: Default = ...) -> Union[List[Str], Default]: ...

    @abstractmethod
    def get_all_ints(self, name: str, default: Default = ...) -> Union[List[Int], Default]: ...

    @abstractmethod
    def get_all_floats(self, name: str, default: Default = ...) -> Union[List[Float], Default]: ...

    @abstractmethod
    def get_all_float2s(self, name: str, default: Default = ...) -> Union[List[Float2], Default]: ...

    @abstractmethod
    def get_all_float3s(self, name: str, default: Default = ...) -> Union[List[Float3], Default]: ...

    @abstractmethod
    def get_all_float4s(self, name: str, default: Default = ...) -> Union[List[Float4], Default]: ...

    @abstractmethod
    def get_all_int2s(self, name: str, default: Default = ...) -> Union[List[Int2], Default]: ...

    @abstractmethod
    def get_all_int3s(self, name: str, default: Default = ...) -> Union[List[Int3], Default]: ...

    @abstractmethod
    def get_all_bools(self, name: str, default: Default = ...) -> Union[List[Bool], Default]: ...

    @abstractmethod
    def get_all_colors(self, name: str, default: Default = ...) -> Union[List[Color], Default]: ...

    @abstractmethod
    def get_all_float12s(self, name: str, default: Default = ...) -> Union[List[Float12], Default]: ...

    @abstractmethod
    def get_all_longs(self, name: str, default: Default = ...) -> Union[List[Long], Default]: ...

    def add_str(self, name: str, value: str) -> None: ...

    def add_int(self, name: str, value: int) -> None: ...

    def add_float(self, name: str, value: float) -> None: ...

    def add_float2(self, name: str, x: float, y: float) -> None: ...

    def add_float3(self, name: str, x: float, y: float, z: float) -> None: ...

    def add_float4(self, name: str, x: float, y: float, z: float, w: float) -> None: ...

    def add_int2(self, name: str, x: int, y: int) -> None: ...

    def add_int3(self, name, x, y, z) -> None: ...

    def add_bool(self, name: str, value: bool) -> None: ...

    def add_false(self, name: str) -> None: ...

    def add_true(self, name: str) -> None: ...

    def add_color(self, name: str, r: int, g: int, b: int, a: int = 255) -> None: ...

    def add_float12(self, name: str,
                    rx: float, ry: float, rz: float,
                    ux: float, uy: float, uz: float,
                    fx: float, fy: float, fz: float,
                    px: float, py: float, pz: float,
                    ) -> None: ...

    def add_long(self, name: str, value: int) -> None: ...

    @abstractmethod
    def pairs(self) -> Iterator[Item]: ...

    @abstractmethod
    def check_cycle(self) -> None: ...

PairsGenOf = Callable[['Section'], Iterator[Item]]

class DictSection(OrderedDict[Name, List[Value]], Section):
    @override
    def get(self, name: str, index: int = 0, default: Default = None) -> Union[Value, Default]: ...

    @override
    def get_all(self, name: str, default: Default = ...) -> Union[List[Value], Default]: ...

    @override
    def get_all_sections(self, name: str, default: Default = ...) -> Union[List[Section], Default]: ...

    @override
    def get_all_strs(self, name: str, default: Default = ...) -> Union[List[Str], Default]: ...

    @override
    def get_all_ints(self, name: str, default: Default = ...) -> Union[List[Int], Default]: ...

    @override
    def get_all_floats(self, name: str, default: Default = ...) -> Union[List[Float], Default]: ...

    @override
    def get_all_float2s(self, name: str, default: Default = ...) -> Union[List[Float2], Default]: ...

    @override
    def get_all_float3s(self, name: str, default: Default = ...) -> Union[List[Float3], Default]: ...

    @override
    def get_all_float4s(self, name: str, default: Default = ...) -> Union[List[Float4], Default]: ...

    @override
    def get_all_int2s(self, name: str, default: Default = ...) -> Union[List[Int2], Default]: ...

    @override
    def get_all_int3s(self, name: str, default: Default = ...) -> Union[List[Int3], Default]: ...

    @override
    def get_all_bools(self, name: str, default: Default = ...) -> Union[List[Bool], Default]: ...

    @override
    def get_all_colors(self, name: str, default: Default = ...) -> Union[List[Color], Default]: ...

    @override
    def get_all_float12s(self, name: str, default: Default = ...) -> Union[List[Float12], Default]: ...

    @override
    def get_all_longs(self, name: str, default: Default = ...) -> Union[List[Long], Default]: ...

    @override
    def pairs(self) -> Iterator[Item]: ...

    @override
    def check_cycle(self) -> None: ...

    def __init__(self, init: Iterable[Tuple[str, List[Value]]] = ()) -> None: ...

    @override
    def append(self, item: Item) -> None: ...

    @override
    def add(self, name: str, value: Value) -> None: ...

    def sorted_pairs(self) -> Iterator[Item]: ...

    def bfs_sorted_pairs(self) -> Iterator[Item]: ...

    def names(self) -> Iterator[Name]: ...

    def strings(self) -> Iterator[Str]: ...

    def size(self) -> Size: ...

class Command(Tuple):
    prefix: ClassVar[str]
    sep: Final[ClassVar[str]]
    name: ClassVar[Name]


class Comment(Command):
    def __new__(cls, value: str) -> Self: ...

    @property
    def text(self) -> str: ...

    @classmethod
    def _check(cls, text: str) -> None: ...

    @classmethod
    def of(cls, text: str) -> 'Comment': ...

class LineComment(Comment):
    name: Final[ClassVar[Name]]

def SafeLineComment(text: str) -> LineComment: ...

class BlockComment(Comment):
    name: Final[ClassVar[Name]]

def SafeBlockComment(text: str) -> BlockComment: ...

class Include(Command):
    name: Final[ClassVar[Name]]
    cdk_prefix: Final[ClassVar[str]]
    root_prefix: Final[ClassVar[str]]

    def __new__(cls, value: str) -> Self: ...

    @property
    def path(self) -> Path: ...

ItemPredicate = Callable[[Item], bool]

class ListSection(List[Item], Section):
    @override
    def add(self, name: str, value: Value) -> None: ...

    def add_comment(self, text: str) -> None: ...

    def add_include(self, path: str) -> None: ...

    @override
    def get(self, name: str, index: int = 0, default: Default = None) -> Union[Value, Default]: ...

    @override
    def get_all(self, name: str, default: Default = ...) -> Union[List[Value], Default]: ...

    @override
    def get_all_sections(self, name: str, default: Default = ...) -> Union[List[Section], Default]: ...

    @override
    def get_all_strs(self, name: str, default: Default = ...) -> Union[List[Str], Default]: ...

    @override
    def get_all_ints(self, name: str, default: Default = ...) -> Union[List[Int], Default]: ...

    @override
    def get_all_floats(self, name: str, default: Default = ...) -> Union[List[Float], Default]: ...

    @override
    def get_all_float2s(self, name: str, default: Default = ...) -> Union[List[Float2], Default]: ...

    @override
    def get_all_float3s(self, name: str, default: Default = ...) -> Union[List[Float3], Default]: ...

    @override
    def get_all_float4s(self, name: str, default: Default = ...) -> Union[List[Float4], Default]: ...

    @override
    def get_all_int2s(self, name: str, default: Default = ...) -> Union[List[Int2], Default]: ...

    @override
    def get_all_int3s(self, name: str, default: Default = ...) -> Union[List[Int3], Default]: ...

    @override
    def get_all_bools(self, name: str, default: Default = ...) -> Union[List[Bool], Default]: ...

    @override
    def get_all_colors(self, name: str, default: Default = ...) -> Union[List[Color], Default]: ...

    @override
    def get_all_float12s(self, name: str, default: Default = ...) -> Union[List[Float12], Default]: ...

    @override
    def get_all_longs(self, name: str, default: Default = ...) -> Union[List[Long], Default]: ...

    @override
    def pairs(self) -> Iterator[Item]: ...

    @override
    def check_cycle(self) -> None: ...

    def get_index(self, p: ItemPredicate) -> Optional[int]: ...

    def get_indices(self, p: ItemPredicate) -> List[int]: ...

    def get_item(self, p: ItemPredicate) -> Optional[Item]: ...

    def get_items(self, p: ItemPredicate) -> List[Item]: ...

    def set_item(self, p: ItemPredicate, item: Item) -> None: ...

    def remove_comments(self) -> None: ...

    def include_files(self, working_path: Path = Path.cwd(), cdk_path: Optional[Path] = None, root_path: Optional[Path] = None) -> None: ...

    def __call__(self) -> DictSection: ...
